server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
#    gateway:
#        routes:
#          - id: r1
#            uri: http://localhost:8090
#            predicates:
#              - Path= /customers/**
#          - id: r2
#            uri: http://localhost:8091
#            predicates:
#              - Path= /terrains/**
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path= /customers/**
        - id: r2
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path= /terrains/**
